# Generated by Django 2.0.5 on 2018-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarmaking', '0004_auto_20180509_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
