# Generated by Django 2.0.5 on 2018-05-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guitarmaking', '0004_auto_20180509_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='learning',
        ),
        migrations.AddField(
            model_name='learning',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning', to='guitarmaking.Schedule'),
        ),
    ]
