# Generated by Django 2.0.4 on 2018-04-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neckbodyjoint',
            name='features',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='neckbodyjoint',
            name='history',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='neckbodyjoint',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
